apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../application-controller-roles
- argocd-application-controller-statefulset.yaml
- argocd-metrics.yaml
- argocd-application-controller-network-policy.yaml

# Uncomment to enable Redis file-mounted credentials for application-controller
#patches:
#  - path: overlays/file-mount/controller-file-mount-patch.yaml