apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-redis-configmap
  labels:
    app.kubernetes.io/name: argocd-redis
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: redis
data:
  init.sh: |
    echo "$(date) Start..."
    REDIS_CONF=/data/conf/redis.conf
  
    mkdir -p /data/conf

    echo "Copying default redis config.."
    cp /readonly-config/redis.conf "${REDIS_CONF}"

    # Determine which source to use for the Redis password
    if [ -n "${REDIS_CREDS_FILE_PATH}" ] && [ -f "${REDIS_CREDS_FILE_PATH}/auth" ]; then
        REDIS_PASSWORD_FILE="${REDIS_CREDS_FILE_PATH}/auth"
        file_auth="$(< "$REDIS_PASSWORD_FILE" tr -d '\n\r')"
        if [ -n "$file_auth" ]; then
            echo "Retrieved Redis credentials from file"
            REDIS_PASSWORD="$file_auth"
        else
            echo "WARNING: Redis credential file is empty"
            # fall through to try env
        fi
    fi
    if [ -n "${REDIS_PASSWORD:-}" ]; then
        echo "Retrieved Redis password from environment"
    else
        echo "WARNING: Redis password not set via file or environment."
    fi
    }

    echo "Setting redis auth values.."
    ESCAPED_AUTH=$(echo "${REDIS_PASSWORD}" | sed -e 's/[\/&]/\\&/g');
    sed -i "s/replace-default-auth/${ESCAPED_AUTH}/" "${REDIS_CONF}"

    echo "$(date) Ready..."
  redis.conf: |
    # Redis configuration file template

    dir "/data"
    port 6379
    bind 0.0.0.0
    appendonly no
    save ""
    requirepass replace-default-auth
