apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-redis-ha-haproxy
spec:
  template:
    spec:
      containers:
      - name: haproxy
        env:
        - name: AUTH
          $patch: delete