apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-redis
spec:
  template:
    spec:
      initContainers:
        - name: config-init
          image: redis:7.2.7-alpine
          command: 
          - "sh"
          - "/readonly-config/init.sh"
          env:
            - name: REDIS_CREDS_FILE_PATH
              value: "/redis-creds"
          volumeMounts:
            - name: config
              mountPath: /readonly-config
            - name: data
              mountPath: /data
            - name: redis-creds
              mountPath: /run/secrets/argocd/redis-auth
              readOnly: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
      containers:
      - name: redis
        args:
        - "redis-server"
        - "/data/conf/redis.conf"
        volumeMounts:
          - name: data
            mountPath: /data
      volumes:
        - name: config
          configMap:
            name: argocd-redis-configmap
        - name: data
          emptyDir: {}
        - name: redis-creds
          secret:
            secretName: argocd-redis
            items:
              - key: auth
                path: auth
            optional: false