apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
spec:
  template:
    spec:
      containers:
      - name: argocd-server
        env:
          - name: REDIS_CREDS_FILE_PATH
            value: "/redis-creds"
        volumeMounts:
          - name: redis-creds
            mountPath: /redis-creds
            readOnly: true
      volumes:
        - name: redis-creds
          secret:
            secretName: argocd-redis
            items:
              - key: auth
                path: auth
            optional: false